# Generated by Django 3.0.7 on 2020-06-12 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_article_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ManyToManyField(default='هیچکدام', related_name='related_name', to='blog.Category', verbose_name='دسته بندی'),
        ),
    ]
