# Generated by Django 3.0.7 on 2020-06-12 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200612_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ManyToManyField(blank=True, default='هیچکدام', null=True, related_name='related_name', to='blog.Category', verbose_name='دسته بندی'),
        ),
    ]
