# Generated by Django 3.0.7 on 2020-06-12 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200612_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent_related_name', to='blog.Category', verbose_name='زیردسته'),
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, related_name='related_name', to='blog.Category', verbose_name='دسته بندی'),
        ),
    ]
