# Generated by Django 3.0.7 on 2020-07-01 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20200701_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='optional_description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات اختیاری'),
        ),
    ]
