# Generated by Django 3.0.7 on 2020-06-29 03:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200629_0806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='spesial_user',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 29, 3, 50, 14, 621557, tzinfo=utc), verbose_name='کاریر ویژه تا'),
        ),
    ]
