# Generated by Django 3.0.7 on 2020-06-29 03:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200629_0820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='spesial_user',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='کاریر ویژه تا'),
        ),
    ]
