# Generated by Django 3.0.7 on 2020-06-29 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200629_0820'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='spesial_user',
            new_name='special_user',
        ),
    ]
